name="blog"
version="0.1.1"
author="qxg"
email="qinxiaoguang01@gmail.com"

[redis]
ip="127.0.0.1"
port=6379

[server]
port=8080
page_url="http://localhost"
server_url="http://localhost:8080"
web_path=${web_path}

[mongo]
ip="127.0.0.1"
port=27017
db_name="blog"

[github]
client_id="eccd2bd134009643887a"
client_secret="160713e18d4d2c19d752513c5db48c0df609611b"
